language: node_js
sudo: false
node_js:
  - "11.13.0"
install:
  - yarn install
stages:
  - test
  - build
  - lint
jobs:
  include:
    - stage: test
      script: yarn test
    - # stage test
      script: yarn prettier:check
    - # stage test
      script: yarn lint
    - stage: build
      script: yarn build
